server:
  port: 2333

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      snapshot: false
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      local: true
      http: true
